### PR TITLE
Bug/empty notes should not have semikolon

### LINKED ISSUE #146: Copied notes have prepended ; if first work item is empty
If first work item of a project is empty and the second one has a description, the copied notes will look like "; <description work2>". The prepended ; should not exists. ; should only be added between notes with content

### PR DESCRIPTION
**Pull request by DavidDamke**
fixes #146

### CODE REVIEW

File: src/main/java/de/doubleslash/keeptime/view/ProjectReport.java [hunk 1]
```diff
@@ -41,11 +41,11 @@ public ProjectReport(final int size) {
 
    public void appendToWorkNotes(final String currentWorkNote) {
       this.numberOfNotes++;
+      this.sb.append(currentWorkNote.trim());
       if (!currentWorkNote.isEmpty()) {
-         if (this.numberOfNotes > 1) {
+         if (this.size>1) {
```
Comment (Death111) [inline src/main/java/de/doubleslash/keeptime/view/ProjectReport.java:46]: we have tests which needs to be
a) checked if still working (pipeline fails, but not sure why. logs do not load currently)
b) extended with new behavior

**Review by Death111 — CHANGES_REQUESTED** [review]

File: src/main/java/de/doubleslash/keeptime/view/ProjectReport.java [hunk 2]
```diff
@@ -41,14 +41,22 @@ public ProjectReport(final int size) {
 
    public void appendToWorkNotes(final String currentWorkNote) {
       this.numberOfNotes++;
+      this.sb.append(currentWorkNote.trim());
```
Comment (Death111) [inline src/main/java/de/doubleslash/keeptime/view/ProjectReport.java:44]: not sure why you append something and one line later we check if it is empty? so we do add also empty strings?

File: src/main/java/de/doubleslash/keeptime/view/ProjectReport.java [hunk 3]
```diff
@@ -41,14 +41,22 @@ public ProjectReport(final int size) {
...
             this.sb.append(NOTE_DELIMETER);
          }
-         this.sb.append(currentWorkNote.trim());
       } else {
          LOG.debug("Skipping empty note.");
       }
+
+      if(numberOfNotes==this.size){
+         int lastSemiColonIndex = this.sb.lastIndexOf(";");
+         if (lastSemiColonIndex != -1) {
```
Comment (Death111) [inline src/main/java/de/doubleslash/keeptime/view/ProjectReport.java:55]: this logic seems really complex. I am also wondering how this works with the "lastIndexOf" and "deleteCharAt" "setLength" methods. quite confusing (for not adding a ; at the start).

As we have nice tests already I suggest to redo the whole logic here. Using class StringJoiner instead of StringBuilder ;) (I found that by accident. I know there exists some helper function to join a list of strings with a specified delimiter - but found this class which does the same thing basically.

**Review by Death111 — CHANGES_REQUESTED** [review]

File: src/main/java/de/doubleslash/keeptime/view/ProjectReport.java (hunk 3 above)
Comment (DavidDamke) [reply src/main/java/de/doubleslash/keeptime/view/ProjectReport.java]: I changed the logic it is much simpler now and works.

Comment (DavidDamke) [reply src/main/java/de/doubleslash/keeptime/view/ProjectReport.java]: Can I delete this getter ?    
public int getNumberOfNotes() {
      return this.numberOfNotes;
I it is not used and we do not include the numberOfNotes anymore

Comment (Death111) [reply src/main/java/de/doubleslash/keeptime/view/ProjectReport.java]: if not needed we can remove it :)

**Review by Death111 — APPROVED** [review]
